Repository compomics/ms2rescore, pull requests merged in 2022-04, with the labels that each got.

#57 PeaksXPro output compatibility
  ms2rescore/__init__.py
  ms2rescore/id_file_parser.py
  ms2rescore/parse_mgf.py
Labels: bug, enhancement

#62 GUI shell fix
  ms2rescore/gui.py
  ms2rescore/package_data/img/__init__.py
  ms2rescore/rescore_core.py
Labels: GUI

#63 Minor fixes
  README.md
  ms2rescore/gui.py
  ms2rescore/percolator.py
  setup.py
Labels: refactoring
