Repository compomics/ms2rescore, pull requests merged in 2022-08, with the labels that each got.

#72 Rich CLI output; Percolator changes; minor fixes
  README.md
  ms2rescore/__init__.py
  ms2rescore/__main__.py
  ms2rescore/config_parser.py
  ms2rescore/gui.py
  ms2rescore/id_file_parser.py
  ms2rescore/parse_mgf.py
  ms2rescore/rescore_core.py
  ms2rescore/setup_logging.py
  setup.py
Labels: enhancement, refactoring

#71 Plotting percolator weights
  README.md
  ms2rescore/__init__.py
  ms2rescore/plotting.py
  setup.py
Labels: enhancement

#75 Fix gui maxquant modification parsing error
  ms2rescore/gui.py
Labels: bug

#76 Fix gui maxquant modification parsing error
  ms2rescore/gui.py
Labels: bug
