Repository compomics/ms2rescore, pull requests merged in 2024-09, with the labels that each got.

#175 Improve GUI user experience
  ms2rescore/gui/app.py
  ms2rescore/gui/function2ctk.py
  ms2rescore/gui/widgets.py
  ms2rescore/package_data/img/comments_icon_black.png
  ms2rescore/package_data/img/comments_icon_white.png
  ms2rescore/package_data/img/docs_icon_black.png
  ms2rescore/package_data/img/docs_icon_white.png
  ms2rescore/package_data/img/github_icon_black.png
  ms2rescore/package_data/img/github_icon_white.png
  ms2rescore/package_data/ms2rescore-gui-theme.json
Labels: GUI

#187 Docs: Fix README URLs to documentation pages
  README.md
Labels: documentation

#189 Update dependencies
  .github/workflows/test.yml
  ms2rescore/__init__.py
  pyproject.toml
Labels: dependencies

#186 Switch to FlashLFQ output from psm_utils
  docs/source/config_schema.md
  examples/msgfplus-ms2rescore.json
  examples/msgfplus-ms2rescore.toml
  ms2rescore/core.py
  ms2rescore/gui/app.py
  ms2rescore/package_data/config_default.json
  ms2rescore/package_data/config_default_tims.json
  ms2rescore/package_data/config_schema.json
  ms2rescore/rescoring_engines/mokapot.py
Labels: enhancement

#191 Fix incorrect decoy pattern configuration in docs
  docs/source/userguide/configuration.rst
Labels: documentation
