Repository compomics/ms2rescore, pull requests merged in 2025-04, with the labels that each got.

#215 Add IM2Deep to citations GUI
  ms2rescore/gui/app.py
Labels: enhancement, GUI

#217 CI: Update action versions
  .github/workflows/publish.yml
  .github/workflows/test.yml
Labels: CI

#224 Fix Numpy v2 compatibility (backport of #223, fixes #219)
  ms2rescore/__init__.py
  ms2rescore/feature_generators/deeplc.py
Labels: bug
